### ISSUE TITLE
Penggunaan kata-kata dari bahasa inggris?

### ISSUE THREAD

**Issue by yoga1234** [javascript-tutorial/id.javascript.info#131]
Hello kawan-kawan penerjemah,
Karena ada beberapa yang aktif dalam penerjemahan saya lihat menggunakan kata-kata yang berbeda-beda.
Kayanya harus ada kata/kalimat yang harus dipatok agar tidak diterjemahkan kedalam bahasa Indonesia, agar semua terjemahannya satu irama. hehehe
Soalnya ada yang pake kata "senarai" ada yang pake "array", ada yang "event" ada yang "peristiwa" dll, jadi tiap file me referensi ke kata yang berbeda-beda.

Ada masukan mungkin atau ada yang setuju bikin list kata yang tidak boleh diterjemahkan?

**Comment by hendraaagil** [comment]
Kalau saya sendiri memakai referensi berikut :
- [https://github.com/reactjs/id.reactjs.org/wiki/Glosarium](https://github.com/reactjs/id.reactjs.org/wiki/Glosarium)
- [https://kateglo.com/](https://kateglo.com/)

**Comment by tegarjgap** [comment]
yap. bikin rules nya gitu hehe

**Comment by yoga1234** [comment]
> Kalau saya sendiri memakai referensi berikut :
> 
> * https://github.com/reactjs/id.reactjs.org/wiki/Glosarium
> * https://kateglo.com/

Mantap nih referensinya, thnks gan..

**Comment by hendraaagil** [comment]
> > Kalau saya sendiri memakai referensi berikut :
> > 
> > * https://github.com/reactjs/id.reactjs.org/wiki/Glosarium
> > * https://kateglo.com/
> 
> Mantap nih referensinya, thnks gan..

siap, sama sama

**Comment by babul28** [comment]
> Kalau saya sendiri memakai referensi berikut :
> 
> * https://github.com/reactjs/id.reactjs.org/wiki/Glosarium
> * https://kateglo.com/

Waahh bisa dijadikan referensi ini, terima kasih. sebelumnya aku gunakan ini https://github.com/isatrio/Panduan-Penerjemahan/blob/master/glosarium.md

**Comment by abdmmar** [comment]
> Kalau saya sendiri memakai referensi berikut :
> 
> * https://github.com/reactjs/id.reactjs.org/wiki/Glosarium
> * https://kateglo.com/

Tambahan referensi:
https://github.com/vuejs-id/docs/blob/master/GLOSARIUM.md

**Comment by juuni26** [comment]
untuk sesuatu seperti array dan event kalo bisa ga perlu diterjemahin. itu istilahnya apa ya, sesuatu yang sudah biasa diserap dari istilah pemograman. saran aja sih, soalnya rada aneh kalo baca senarai di istilah pemograman 😄
