### ISSUE TITLE
Regular expressions: Patterns and flags

### ISSUE THREAD

**Issue by iamfaizalandyka** [javascript-tutorial/id.javascript.info#25]
**Regular expressions**: Patterns and flags

**Comment by iamfaizalandyka** [comment]
Hi @iliakan @thickkoezz
Please check my PR https://github.com/javascript-tutorial/id.javascript.info/pull/26 😄

**Comment by iliakan** [comment]
@thickkoezz are you available?

By the way, I will be updating Regexp part, please translate something else meanwhile =)

**Comment by iliakan** [comment]
@iamfaizalandyka if @thickkoezz  doesn't respond for a long time, for some reason, please mention me.

**Comment by iamfaizalandyka** [comment]
Ok, I'll finish the `Regular expressions: Methods of RegEx and String` first, after that I'll translate other page 😄

**Comment by iliakan** [comment]
@iamfaizalandyka please hang on till the update =) The text will be changes, you'll need to review and retranslate, it's easier just to translate something else meanwhile.

**Comment by iamfaizalandyka** [comment]
Ok, I'll hold it
